import { z } from 'zod'

/**
 * ID format conventions (docs/dev-file/03-Data-Model.md §1.1):
 *
 *   - `firmId` / `userId` / actor IDs are issued by better-auth and use
 *     nanoid (variable length, alphanumeric). DO NOT enforce UUID here.
 *   - Application-owned rows (`client.id`, `obligation_instance.id`,
 *     `migration_batch.id`, audit / evidence rows) are generated by the
 *     server with `crypto.randomUUID()` and DO follow UUID v4.
 *
 * `TenantIdSchema` covers the better-auth side. `EntityIdSchema` covers the
 * app side. Keeping them as named schemas makes the audit trail explicit:
 * a contract reviewer can see at a glance which IDs come from which source.
 */
export const TenantIdSchema = z.string().min(1)
export type TenantId = z.infer<typeof TenantIdSchema>

export const EntityIdSchema = z.string().uuid()
export type EntityId = z.infer<typeof EntityIdSchema>
